services:
  merge-folders:
    build: .
    container_name: merge-folders-app
    ports:
      - "28888:8080"
    volumes:
      - ${DATA_PATH}:/app/data
      - ${CACHE_PATH}:/app/cache
    environment:
      - GIN_MODE=release
    restart: unless-stopped

